- name: uruchom role packages
  hosts: all
  connection: local
  become: true
  vars:
    docker_users:
      - panda
  
    docker_daemon_options:
      insecure-registries : ["192.168.44.44:8082"]

  roles:
    - packages
    - user
    - geerlingguy.docker
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform

  
